package org.rmit.view.Owner;

public enum OWNER_MENU_OPTION {
    DASHBOARD,
    EDIT_PROFILE,
    LOGOUT,
    PROPERTIES_MANAGER,
    ADD_PROPERTY,
    UPDATE_PROPERTY,
    HOST_MANAGER,
    NOTIFICATION,
}
