package org.rmit.view.Admin;

public enum ADMIN_MENU_OPTION {
    RENTER_MANAGER,
    DASHBOARD,
    EDIT_PROFILE,
    AGREEMENT_MANAGER,
    HOST_MANAGER,
    OWNER_MANAGER,
    PAYMENT_MANAGER,
    ADMIN_MANAGER,
    PROPERTY_MANAGER,
    LOGOUT
}
